#!/bin/bash
#
#SBATCH --job-name=dddd-iters # Job name for tracking
#SBATCH --partition=falcon,gecko,eagle     # Partition you wish to use (see above for list)
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6     # Number of CPU threads used by your job
#SBATCH --gres=gpu:1           # Number of GPUs to use 
#SBATCH --time=2-00:00:00      # Job time limit set to 2 days (48 hours)
#
#SBATCH --mail-type=END,FAIL,TIME_LIMIT_80 # Events to send email on, remove if you don't want this
#SBATCH --output=sbatch/info.out # Standard out from your job
#SBATCH --error=sbatch/info.err  # Standard error from your job

## Initialisation ##
source /etc/profile.d/modules.sh
source /etc/profile.d/conda.sh

## Execute your program(s) ##
module load CUDA
conda activate DDDD

python3 ./src/unetinfo.py